--- drivers/clk/msm/Makefile
+++ drivers/clk/msm/Makefile
@@ -61,10 +61,10 @@ obj-$(CONFIG_ARCH_MSM8916)	+= clock-a7.o
 obj-$(CONFIG_ARCH_MSM8909)	+= clock-a7.o
 obj-$(CONFIG_ARCH_MSM8916)	+= clock-cpu-8939.o
 obj-$(CONFIG_ARCH_MSM8916)	+= clock-cpu-8936.o
-#obj-$(CONFIG_ARCH_MSM8916)	+= clock-gcc-8952.o
-#obj-$(CONFIG_ARCH_MSM8916)	+= clock-gcc-8953.o
+obj-$(CONFIG_ARCH_MSM8916)	+= clock-gcc-8952.o
+obj-$(CONFIG_ARCH_MSM8916)	+= clock-gcc-8953.o
 obj-$(CONFIG_ARCH_MSM8916)	+= clock-rcgwr.o
-#obj-$(CONFIG_ARCH_MSM8916)      += clock-cpu-8953.o
+obj-$(CONFIG_ARCH_MSM8916)      += clock-cpu-8953.o
 obj-$(CONFIG_ARCH_MSM8916)	+= clock-cpu-8976.o
 
 # ACPU: Krait specific
